version: "3.4"
volumes:
  shared-volume:
services:
  nacos:
    container_name: "nacos"
    image: nacos/nacos-server:${NACOS_VERSION}
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: 1
    ports:
      - "8848:8848"
      - "9848:9848"
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST 'http://127.0.0.1:8848/nacos/v1/auth/login' -d 'username=nacos&password=nacos' | grep '{'"]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 5s
  swoole:
    container_name: "swoole"
    depends_on:
      - nacos
    environment:
      IMI_NACOS_HOST: ${IMI_NACOS_HOST}
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
    working_dir: /imi
    command: tail -f /dev/null
